runtime: go112
service: default

instance_class: F2

inbound_services:
  - warmup

handlers:
  - url: /_ah/*
    script: auto
    secure: always
    login: admin
  - url: /test-admin
    script: auto
    secure: always
    login: admin
  - url: /.*
    script: auto
    secure: always