runtime: go113
service: default

instance_class: F2

inbound_services:
  - warmup

handlers:
  - url: /_ah/*
    script: auto
    secure: always
  - url: /test-admin
    script: auto
    secure: always
  - url: /.*
    script: auto
    secure: always

env_variables:
  REDISHOST: ''
  REDISPORT: ''
  REDISDB: '0'
  DS_KIND: ""

vpc_access_connector:
  name: ''